# TODO: replace the title with the name of your restaurant!
title: "Cade"
# TODO: write your restaurateur alter ego name below, or your own name
author: Cornelius Banez
# TODO: write your Google Analytics tracking ID below
google_analytics: G-VS5E472MSG

theme: minima

collections:
  explorations:
    output: true
